"""Crash-safe synchronization for tracker projections.

The local tracker ledger is the source of truth.  CSV and Google Sheets are
projections behind the :class:`FreshStore` interface.  This module keeps the
coordination policy in one deep module so callers do not need to know about
digests, retries, ownership, or conflict handling.

The interface deliberately favors strong local invariants and eventual
projection consistency. Google Sheets cannot participate in a real database
transaction, so every remote write is guarded by a precondition and recorded
in an operation ledger that can be replayed after a crash. Additive Sheets
writes use an append-only projection; full read-back remains the migration and
reconciliation path.
"""

from __future__ import annotations

import json
import hashlib
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable
from uuid import uuid4

from tools.io_utils import atomic_write_json
from tools.job_urls import normalize_job_url
from tools.workflow.fresh_store import (
    FreshSnapshot,
    FreshStore,
    SnapshotConflict,
    _headers_for_rows,
    merge_fresh_rows,
)
from tools.fresh_24h.batch_mark import demote_previous_batch

SYNC_SCHEMA_VERSION = 1

# Fields generated by the system.  Unknown fields are deliberately not
# silently imported from a remote projection; they need explicit review.
SYSTEM_FIELDS = frozenset(
    {
        "岗位编号",
        "job_id",
        "链接",
        "url",
        "职位",
        "title",
        "公司",
        "company",
        "来源",
        "source",
        "简述",
        "teaser",
        "CareerOps分数",
        "匹配分",
        "pass1_score",
        "pass2_score",
        "final_score",
        "评估状态",
        "assessment_status",
        "assessment_hash",
        "JD深度",
        "jd_depth",
        "抓取时间",
        "扫描时间",
        "scan_id",
        "run_id",
        "publisher_type",
        "publisher_name",
        "employer_name",
        "公司简介",
        "company_brief",
        "language_gate",
        "salary_review",
        "provisional_needs_jd",
        "待审-JD不足",
    }
)

USER_FIELDS = frozenset(
    {
        "状态",
        "投递状态",
        "是否投递",
        "备注",
        "用户备注",
        "跟进",
        "面试结果",
        "我的判断",
        "优先级调整",
        "user_status",
        "application_status",
        "user_note",
        "notes",
        "follow_up",
        "interview_outcome",
        "user_priority",
    }
)


class SyncError(RuntimeError):
    """Base class for synchronization failures."""


class SyncConflict(SyncError):
    """A remote or local snapshot changed unexpectedly."""


class SyncOperationNotFound(SyncError):
    """The requested operation is not present in the local ledger."""


def _now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _safe(value: str) -> str:
    return "".join(ch if ch.isalnum() or ch in {"-", "_", "."} else "_" for ch in value)[:120]


def _hash(value: Any) -> str:
    raw = json.dumps(value, ensure_ascii=False, sort_keys=True, default=str)
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()


def _row_key(row: dict[str, Any]) -> str | None:
    url = normalize_job_url(str(row.get("链接") or row.get("url") or "").strip())
    if url:
        return f"url:{url}"
    job_id = str(row.get("岗位编号") or row.get("job_id") or "").strip()
    if job_id:
        return f"id:{job_id}"
    return None


def _row_map(rows: Iterable[dict[str, Any]]) -> dict[str, dict[str, Any]]:
    return {key: dict(row) for row in rows if (key := _row_key(row))}


def _snapshot_payload(snapshot: FreshSnapshot) -> dict[str, Any]:
    return {
        "title": snapshot.title,
        "headers": list(snapshot.headers),
        "rows": [dict(row) for row in snapshot.rows],
        "digest": snapshot.digest,
    }


def _snapshot_from_payload(payload: dict[str, Any]) -> FreshSnapshot:
    return FreshSnapshot(
        title=str(payload.get("title") or "fresh"),
        headers=list(payload.get("headers") or []),
        rows=[dict(row) for row in payload.get("rows") or []],
    )


def operation_root(workspace: Path) -> Path:
    return Path(workspace) / "02_Tracker" / "workflow" / "sync_operations"


def ledger_root(workspace: Path) -> Path:
    return Path(workspace) / "02_Tracker" / "workflow" / "ledger"


def projection_root(workspace: Path) -> Path:
    return Path(workspace) / "02_Tracker" / "workflow" / "projections"


def conflict_root(workspace: Path) -> Path:
    return Path(workspace) / "02_Tracker" / "workflow" / "sync_conflicts"


def _operation_path(workspace: Path, operation_id: str) -> Path:
    return operation_root(workspace) / f"{_safe(operation_id)}.json"


def _ledger_path(workspace: Path, title: str) -> Path:
    return ledger_root(workspace) / f"{_safe(title)}.json"


def _projection_path(workspace: Path, title: str, backend: str) -> Path:
    return projection_root(workspace) / _safe(title) / f"{_safe(backend)}.json"


def _read_json(path: Path) -> dict[str, Any] | None:
    if not path.is_file():
        return None
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    return value if isinstance(value, dict) else None


def _backend_name(store: Any) -> str:
    name = store.__class__.__name__
    return {
        "GSheetFreshStore": "gsheet",
        "LocalCsvFreshStore": "csv",
        "FileFreshStore": "file",
        "MemoryFreshStore": "memory",
    }.get(name, name.casefold())


@dataclass
class SyncOperation:
    operation_id: str
    title: str
    backend: str
    source_digest: str
    target_before_digest: str
    target_after_digest: str = ""
    status: str = "planned"
    run_id: str = ""
    source_snapshot: dict[str, Any] | None = None
    error: str = ""
    conflicts: list[dict[str, Any]] | None = None
    attempts: int = 0
    created_at: str = ""
    updated_at: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "schema_version": SYNC_SCHEMA_VERSION,
            "operation_id": self.operation_id,
            "title": self.title,
            "backend": self.backend,
            "source_digest": self.source_digest,
            "target_before_digest": self.target_before_digest,
            "target_after_digest": self.target_after_digest,
            "status": self.status,
            "run_id": self.run_id,
            "source_snapshot": self.source_snapshot,
            "error": self.error,
            "conflicts": list(self.conflicts or []),
            "attempts": self.attempts,
            "created_at": self.created_at,
            "updated_at": self.updated_at,
        }

    @classmethod
    def from_dict(cls, value: dict[str, Any]) -> "SyncOperation":
        return cls(
            operation_id=str(value.get("operation_id") or ""),
            title=str(value.get("title") or "fresh"),
            backend=str(value.get("backend") or "unknown"),
            source_digest=str(value.get("source_digest") or ""),
            target_before_digest=str(value.get("target_before_digest") or ""),
            target_after_digest=str(value.get("target_after_digest") or ""),
            status=str(value.get("status") or "planned"),
            run_id=str(value.get("run_id") or ""),
            source_snapshot=value.get("source_snapshot") if isinstance(value.get("source_snapshot"), dict) else None,
            error=str(value.get("error") or ""),
            conflicts=list(value.get("conflicts") or []),
            attempts=int(value.get("attempts") or 0),
            created_at=str(value.get("created_at") or ""),
            updated_at=str(value.get("updated_at") or ""),
        )


class TrackerLedger:
    """Durable local source of truth for a fresh tracker title."""

    def __init__(self, workspace: Path, title: str) -> None:
        self.workspace = Path(workspace)
        self.title = title
        self.path = _ledger_path(self.workspace, title)

    def exists(self) -> bool:
        return self.path.is_file()

    def read(self) -> FreshSnapshot:
        data = _read_json(self.path)
        if not data:
            return FreshSnapshot(title=self.title, headers=[], rows=[])
        return _snapshot_from_payload(data)

    def write(self, snapshot: FreshSnapshot, *, expected_digest: str | None = None) -> FreshSnapshot:
        current = self.read()
        if expected_digest is not None and current.digest != expected_digest:
            raise SyncConflict("local_ledger_digest_changed")
        payload = _snapshot_payload(snapshot)
        payload["updated_at"] = _now()
        atomic_write_json(self.path, payload)
        return self.read()

    def bootstrap(self, snapshot: FreshSnapshot) -> FreshSnapshot:
        if self.exists():
            return self.read()
        return self.write(snapshot)


class SyncLedger:
    """Operation ledger and projection snapshots for crash recovery."""

    def __init__(self, workspace: Path) -> None:
        self.workspace = Path(workspace)

    def save(self, operation: SyncOperation) -> SyncOperation:
        operation.updated_at = _now()
        if not operation.created_at:
            operation.created_at = operation.updated_at
        atomic_write_json(_operation_path(self.workspace, operation.operation_id), operation.to_dict())
        return operation

    def load(self, operation_id: str) -> SyncOperation:
        data = _read_json(_operation_path(self.workspace, operation_id))
        if not data:
            raise SyncOperationNotFound(operation_id)
        return SyncOperation.from_dict(data)

    def list(self, *, title: str | None = None) -> list[SyncOperation]:
        root = operation_root(self.workspace)
        if not root.is_dir():
            return []
        result: list[SyncOperation] = []
        for path in sorted(root.glob("*.json"), key=lambda p: p.stat().st_mtime, reverse=True):
            data = _read_json(path)
            if not data:
                continue
            operation = SyncOperation.from_dict(data)
            if title is None or operation.title == title:
                result.append(operation)
        return result

    def read_projection(self, title: str, backend: str) -> FreshSnapshot | None:
        data = _read_json(_projection_path(self.workspace, title, backend))
        return _snapshot_from_payload(data) if data else None

    def write_projection(self, title: str, backend: str, snapshot: FreshSnapshot) -> None:
        path = _projection_path(self.workspace, title, backend)
        payload = _snapshot_payload(snapshot)
        payload["backend"] = backend
        payload["updated_at"] = _now()
        atomic_write_json(path, payload)


def merge_system_rows(existing: list[dict[str, Any]], incoming: list[dict[str, Any]]) -> tuple[list[dict[str, Any]], dict[str, int]]:
    """Merge new system rows without overwriting user-owned fields."""

    result = [dict(row) for row in existing]
    index = {_row_key(row): pos for pos, row in enumerate(result) if _row_key(row)}
    added = 0
    updated = 0
    kept = 0
    for incoming_row in incoming:
        key = _row_key(incoming_row)
        if not key or key not in index:
            result.append(dict(incoming_row))
            if key:
                index[key] = len(result) - 1
            added += 1
            continue
        current = result[index[key]]
        changed = False
        for field, value in incoming_row.items():
            if field in USER_FIELDS:
                continue
            if current.get(field) != value:
                current[field] = value
                changed = True
        if changed:
            updated += 1
        else:
            kept += 1
    return result, {"added": added, "updated": updated, "kept": kept, "total": len(result)}


def _diff_snapshots(base: FreshSnapshot | None, local: FreshSnapshot, remote: FreshSnapshot) -> dict[str, Any]:
    """Return row/field differences against the last verified projection."""

    base_map = _row_map(base.rows if base else [])
    local_map = _row_map(local.rows)
    remote_map = _row_map(remote.rows)
    conflicts: list[dict[str, Any]] = []
    local_changes: list[dict[str, Any]] = []
    remote_changes: list[dict[str, Any]] = []
    local_only: list[str] = []
    remote_only: list[str] = []

    for key in sorted(set(base_map) | set(local_map) | set(remote_map)):
        base_row = base_map.get(key, {})
        local_row = local_map.get(key)
        remote_row = remote_map.get(key)
        if local_row is None and remote_row is not None and key not in base_map:
            remote_only.append(key)
            continue
        if remote_row is None and local_row is not None and key not in base_map:
            local_only.append(key)
            continue
        for field in sorted(set(base_row) | set(local_row or {}) | set(remote_row or {})):
            base_value = base_row.get(field, "")
            local_value = (local_row or {}).get(field, "")
            remote_value = (remote_row or {}).get(field, "")
            local_changed = local_value != base_value
            remote_changed = remote_value != base_value
            if not local_changed and not remote_changed:
                continue
            item = {
                "row_key": key,
                "field": field,
                "base": base_value,
                "local": local_value,
                "remote": remote_value,
                "owner": "system" if field in SYSTEM_FIELDS else ("user" if field in USER_FIELDS else "unknown"),
            }
            if local_changed and remote_changed and local_value != remote_value:
                conflicts.append({**item, "reason": "both_changed"})
            elif local_changed:
                local_changes.append(item)
            else:
                remote_changes.append(item)
    return {
        "base_digest": base.digest if base else "",
        "local_digest": local.digest,
        "remote_digest": remote.digest,
        "conflicts": conflicts,
        "local_changes": local_changes,
        "remote_changes": remote_changes,
        "local_only": local_only,
        "remote_only": remote_only,
    }


class SyncCoordinator:
    """Deep synchronization module used by push, status, reconcile and pull."""

    def __init__(self, workspace: Path) -> None:
        self.workspace = Path(workspace)
        self.operations = SyncLedger(self.workspace)

    def _write_conflict_report(self, title: str, payload: dict[str, Any]) -> str:
        path = conflict_root(self.workspace) / _safe(title) / f"{datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')}-{uuid4().hex[:8]}.json"
        payload = {
            "schema_version": SYNC_SCHEMA_VERSION,
            "title": title,
            "created_at": _now(),
            **payload,
        }
        atomic_write_json(path, payload)
        return str(path)

    def _prepare_target(self, title: str, store: FreshStore) -> tuple[TrackerLedger, FreshSnapshot, FreshSnapshot, str]:
        ledger = TrackerLedger(self.workspace, title)
        target_before = store.read_active()
        if not ledger.exists():
            ledger.bootstrap(target_before)
        local = ledger.read()
        backend = _backend_name(store)
        projection = self.operations.read_projection(title, backend)
        if projection is None:
            # The first observed remote snapshot is the concurrency baseline;
            # it is not treated as a user edit.
            self.operations.write_projection(title, backend, target_before)
        return ledger, local, target_before, backend

    def push_rows(
        self,
        *,
        title: str,
        incoming: list[dict[str, Any]],
        store: FreshStore,
        run_id: str = "",
        operation_id: str | None = None,
        dry_run: bool = False,
        target_snapshot: FreshSnapshot | None = None,
    ) -> dict[str, Any]:
        if target_snapshot is None:
            ledger, local_before, target_before, backend = self._prepare_target(title, store)
        else:
            # The push adapter already read and digest-bound the target while
            # validating the confirmation proposal. Reuse that snapshot to
            # avoid a duplicate full-sheet read; the append adapter still
            # performs its own immediate precondition check before writing.
            ledger = TrackerLedger(self.workspace, title)
            if not ledger.exists():
                ledger.bootstrap(target_snapshot)
            local_before = ledger.read()
            target_before = target_snapshot
            backend = _backend_name(store)
            projection = self.operations.read_projection(title, backend)
            if projection is None:
                self.operations.write_projection(title, backend, target_before)
        projection = self.operations.read_projection(title, backend) or target_before
        remote_diff = _diff_snapshots(projection, local_before, target_before)
        if remote_diff["conflicts"] or remote_diff["remote_changes"] or remote_diff["remote_only"]:
            report_path = self._write_conflict_report(
                title,
                {"kind": "push_precondition", "backend": backend, **remote_diff},
            )
            return {
                "status": "blocked",
                "blockers": ["remote_changed_requires_reconcile"],
                "conflicts": remote_diff["conflicts"],
                "remote_changes": remote_diff["remote_changes"],
                "remote_only": remote_diff["remote_only"],
                "backend": backend,
                "target_digest": target_before.digest,
                "report_path": report_path,
            }

        existing_keys = {
            _row_key(row) for row in local_before.rows if _row_key(row)
        }
        append_rows = [
            dict(row)
            for row in incoming
            if _row_key(row) and _row_key(row) not in existing_keys
        ]
        # An explicit entry starts a new presentation batch.  Demote the
        # previous batch in the local source-of-truth before merging so the
        # ledger and every projection agree that only the newly entered rows
        # are marked ``本轮新增=是``.  The store applies the same transition to
        # its live projection immediately before inserting the rows.
        merge_base_rows = [dict(row) for row in local_before.rows]
        if append_rows and any((row.get("本轮新增") or "") == "是" for row in append_rows):
            demote_previous_batch(merge_base_rows)
        merged_rows, stats = merge_system_rows(merge_base_rows, incoming)
        if append_rows:
            # New explicit-entry rows are always presented first, even when
            # a schema migration forces the guarded full-replacement path.
            # Previously this ordering was applied only to the fast Sheets
            # adapter, so local CSV and legacy-schema tabs put new rows at the
            # bottom.
            new_keys = {_row_key(row) for row in append_rows if _row_key(row)}
            by_key = {
                _row_key(row): row
                for row in merged_rows
                if _row_key(row) in new_keys
            }
            ordered_new = [by_key[_row_key(row)] for row in append_rows if _row_key(row) in by_key]
            existing_part = [row for row in merged_rows if _row_key(row) not in new_keys]
            merged_rows = ordered_new + existing_part
            if any("行号" in row for row in merged_rows):
                for row_number, row in enumerate(merged_rows, start=2):
                    row["行号"] = str(row_number)
        # The fast Sheets projection is safe only when the confirmed batch is
        # purely additive and the schema is unchanged.  Any update, duplicate,
        # or header migration keeps the guarded full-replacement path.
        append_only = (
            bool(append_rows)
            and len(append_rows) == len(incoming)
            and stats["updated"] == 0
            and _headers_for_rows(local_before.rows, local_before.headers)
            == _headers_for_rows(merged_rows, local_before.headers)
            and callable(getattr(store, "append_rows_if_digest", None))
        )
        if append_only:
            # Sheets inserts the new batch at row 2; the ordering above keeps
            # the local ledger in the same order so its digest remains the
            # projection's digest.
            pass
        merged = FreshSnapshot(
            title=title,
            headers=_headers_for_rows(merged_rows, local_before.headers),
            rows=merged_rows,
        )
        op_id = operation_id or f"sync-{uuid4().hex[:12]}"
        existing = None
        try:
            existing = self.operations.load(op_id)
        except SyncOperationNotFound:
            pass
        if existing is not None:
            if existing.source_digest != merged.digest:
                return {"status": "blocked", "blockers": ["operation_id_reused"], "operation_id": op_id}
            if existing.status == "verified":
                return {
                    "status": "succeeded",
                    "idempotent": True,
                    "operation_id": op_id,
                    "backend": backend,
                    "after_digest": existing.target_after_digest,
                    **stats,
                }

        operation = SyncOperation(
            operation_id=op_id,
            title=title,
            backend=backend,
            source_digest=merged.digest,
            target_before_digest=target_before.digest,
            run_id=run_id,
            source_snapshot=_snapshot_payload(merged),
        )
        self.operations.save(operation)
        if dry_run:
            return {
                "status": "planned",
                "operation_id": op_id,
                "backend": backend,
                "source_digest": merged.digest,
                "target_before_digest": target_before.digest,
                **stats,
            }

        try:
            ledger.write(merged, expected_digest=local_before.digest)
            operation.status = "applying"
            operation.attempts += 1
            self.operations.save(operation)
            if append_only:
                after = store.append_rows_if_digest(
                    append_rows,
                    headers=merged.headers,
                    expected_digest=target_before.digest,
                )
                postconditions = [
                    "projection_write_issued",
                    "source_ledger_committed",
                ]
            else:
                _replace_if_current(store, merged, expected_digest=target_before.digest)
                after = store.read_active()
                if after.digest != merged.digest:
                    raise SyncError("projection_readback_digest_mismatch")
                postconditions = ["projection_read_back", "source_ledger_committed"]
            self.operations.write_projection(title, backend, after)
            operation.status = "verified"
            operation.target_after_digest = after.digest
            self.operations.save(operation)
            return {
                "status": "succeeded",
                "operation_id": op_id,
                "backend": backend,
                "source_digest": merged.digest,
                "target_before_digest": target_before.digest,
                "target_after_digest": after.digest,
                "postconditions": postconditions,
                "write_mode": "append_only" if append_only else "replace_full",
                **stats,
            }
        except (SnapshotConflict, SyncConflict) as exc:
            operation.status = "needs_reconcile"
            operation.error = str(exc)
            self.operations.save(operation)
            return {
                "status": "blocked",
                "operation_id": op_id,
                "backend": backend,
                "blockers": ["sync_conflict"],
                "error": str(exc),
            }
        except Exception as exc:
            operation.status = "needs_reconcile"
            operation.error = str(exc)
            self.operations.save(operation)
            return {
                "status": "failed",
                "operation_id": op_id,
                "backend": backend,
                "blockers": ["sync_projection_failed"],
                "error": str(exc),
            }

    def status(self, *, title: str | None = None) -> dict[str, Any]:
        operations = self.operations.list(title=title)
        pending = [op.to_dict() for op in operations if op.status not in {"verified"}]
        return {
            "status": "succeeded",
            "operations": [op.to_dict() for op in operations],
            "pending": pending,
            "pending_count": len(pending),
        }

    def reconcile(self, *, title: str, store: FreshStore) -> dict[str, Any]:
        ledger, local, remote, backend = self._prepare_target(title, store)
        base = self.operations.read_projection(title, backend)
        diff = _diff_snapshots(base, local, remote)
        unsafe_remote_changes = [
            item for item in diff["remote_changes"] if item.get("owner") != "user"
        ]
        status = "succeeded" if not diff["conflicts"] and not unsafe_remote_changes else "blocked"
        report_path = ""
        if status == "blocked" or diff["remote_changes"] or diff["remote_only"] or diff["local_only"]:
            report_path = self._write_conflict_report(
                title,
                {"kind": "reconcile", "backend": backend, **diff},
            )
        return {
            "status": status,
            "title": title,
            "backend": backend,
            "ledger_digest": local.digest,
            "remote_digest": remote.digest,
            "conflicts": diff["conflicts"],
            "local_changes": diff["local_changes"],
            "remote_changes": diff["remote_changes"],
            "local_only": diff["local_only"],
            "remote_only": diff["remote_only"],
            "blockers": ["sync_conflict"] if diff["conflicts"] or unsafe_remote_changes else [],
            "next_action": "sync_pull_preview" if diff["remote_changes"] else "sync_push_retry",
            "report_path": report_path,
        }

    def pull_user_fields(
        self,
        *,
        title: str,
        store: FreshStore,
        confirmed: bool = False,
        dry_run: bool = False,
    ) -> dict[str, Any]:
        ledger, local, remote, backend = self._prepare_target(title, store)
        base = self.operations.read_projection(title, backend)
        diff = _diff_snapshots(base, local, remote)
        if diff["conflicts"]:
            report_path = self._write_conflict_report(
                title,
                {"kind": "pull_conflict", "backend": backend, **diff},
            )
            return {"status": "blocked", "blockers": ["sync_conflict"], "conflicts": diff["conflicts"], "report_path": report_path}
        blocked_remote = [
            item for item in diff["remote_changes"] if item.get("owner") != "user"
        ]
        if blocked_remote:
            report_path = self._write_conflict_report(
                title,
                {"kind": "pull_system_field_change", "backend": backend, **diff},
            )
            return {
                "status": "blocked",
                "blockers": ["remote_system_field_changed"],
                "remote_changes": blocked_remote,
                "report_path": report_path,
            }
        if not confirmed and not dry_run:
            return {"status": "blocked", "blockers": ["explicit_sync_pull_confirmation_missing"]}
        if dry_run:
            return {
                "status": "planned",
                "backend": backend,
                "user_changes": diff["remote_changes"],
                "remote_only": diff["remote_only"],
            }

        before_local_digest = local.digest
        local_rows = _row_map(local.rows)
        local_positions = {
            key: index for index, row in enumerate(local.rows) if (key := _row_key(row))
        }
        remote_rows = _row_map(remote.rows)
        imported = 0
        updated = 0
        for key, remote_row in remote_rows.items():
            if key not in local_rows:
                row = dict(remote_row)
                row["sync_import_status"] = "needs_local_review"
                local.rows.append(row)
                imported += 1
                continue
            local_row = local.rows[local_positions[key]]
            for field in USER_FIELDS:
                if field in remote_row and local_row.get(field, "") != remote_row.get(field, ""):
                    local_row[field] = remote_row.get(field, "")
                    updated += 1
        local.headers = _headers_for_rows(local.rows, local.headers)
        saved = ledger.write(local, expected_digest=before_local_digest)
        return {
            "status": "succeeded",
            "backend": backend,
            "ledger_digest": saved.digest,
            "imported_rows": imported,
            "updated_user_fields": updated,
            "postconditions": ["local_ledger_committed"],
        }

    def replay(self, *, operation_id: str, store: FreshStore) -> dict[str, Any]:
        operation = self.operations.load(operation_id)
        if operation.status == "verified":
            return {"status": "succeeded", "idempotent": True, "operation_id": operation_id}
        if operation.status not in {"needs_reconcile", "failed", "applying", "planned"}:
            return {"status": "blocked", "blockers": ["operation_not_replayable"], "operation_id": operation_id}
        snapshot = _snapshot_from_payload(operation.source_snapshot or {})
        current = store.read_active()
        projection = self.operations.read_projection(operation.title, operation.backend)
        expected = projection.digest if projection else operation.target_before_digest
        # A crash can happen after the remote write but before the local
        # operation record is marked verified.  Treat an already matching
        # remote snapshot as an idempotent success instead of a conflict.
        if current.digest == snapshot.digest:
            self.operations.write_projection(operation.title, operation.backend, current)
            operation.status = "verified"
            operation.target_after_digest = current.digest
            operation.error = ""
            self.operations.save(operation)
            return {"status": "succeeded", "operation_id": operation_id, "idempotent": True, "target_after_digest": current.digest}
        if current.digest != expected:
            return {
                "status": "blocked",
                "blockers": ["sync_conflict"],
                "operation_id": operation_id,
                "target_digest": current.digest,
                "expected_digest": expected,
            }
        operation.status = "applying"
        operation.attempts += 1
        self.operations.save(operation)
        try:
            _replace_if_current(store, snapshot, expected_digest=current.digest)
            after = store.read_active()
            if after.digest != snapshot.digest:
                raise SyncError("projection_readback_digest_mismatch")
            self.operations.write_projection(operation.title, operation.backend, after)
            operation.status = "verified"
            operation.target_after_digest = after.digest
            operation.error = ""
            self.operations.save(operation)
            return {"status": "succeeded", "operation_id": operation_id, "replayed": True, "target_after_digest": after.digest}
        except Exception as exc:
            operation.status = "needs_reconcile"
            operation.error = str(exc)
            self.operations.save(operation)
            return {"status": "failed", "operation_id": operation_id, "blockers": ["sync_projection_failed"], "error": str(exc)}


def _replace_if_current(store: FreshStore, snapshot: FreshSnapshot, *, expected_digest: str) -> None:
    method = getattr(store, "replace_active_if_digest", None)
    if callable(method):
        method(snapshot, expected_digest)
        return
    current = store.read_active()
    if current.digest != expected_digest:
        raise SnapshotConflict("remote_snapshot_changed")
    store.replace_active(snapshot)
